version: 2.1

executors:
  ruby_executor:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:<< parameters.version_tag >>
    parameters:
      version_tag:
        type: string
        default: 2.7.2

jobs:
  build:
    executor:
      name: ruby_executor
      version_tag: 3.0.0
    environment:
      TZ: "Asia/Tokyo"
    working_directory: ~/working_directory
    steps:
      - checkout
      # TODO: Setup Database, bundle install, bundle exec rubocop, bundle exec rspec
      - run:
          name: Hello, World!
          command: |
            echo 'Hello, World!'
      - run:
          name: Check Ruby version
          command: |
            ruby -v > /tmp/my_artifact
      - run:
          name: Check the installed Ruby path
          command: |
            which ruby > /tmp/bluemoon/which_ruby.txt
      - store_artifacts:
          path: /tmp/my_artifact
          destination: eiyuden
      - store_artifacts:
          path: /tmp/bluemoon

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
