version: 2.1

executors:
  ruby_executor:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:<< parameters.version_tag >>
    parameters:
      version_tag:
        type: string
        default: 2.7.2

jobs:
  build:
    executor:
      name: ruby_executor
      version_tag: 3.0.1
    environment:
      TZ: "Asia/Tokyo"
    working_directory: ~/working_directory
    steps:
      - checkout
      # TODO: Setup Database, bundle install, bundle exec rubocop, bundle exec rspec
      - restore_cache:
          name: Restore RubyGems Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Prepare the artifact directory
          command: |
            mkdir /tmp/bluemoon
      - run:
          name: Hello, World!
          command: |
            echo 'Hello, World!'
      - run:
          name: Check Ruby version
          command: |
            ruby -v > /tmp/my_artifact
      - run:
          name: Check the installed Ruby path
          command: |
            which ruby > /tmp/bluemoon/which_ruby.txt
      - run:
          name: Install the latest Bundler
          command: |
            gem install bundler
      - run:
          name: Bundle install
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          name: Save RubyGems Cache
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Execute RuboCop
          command: |
            bundle exec rubocop
      - store_artifacts:
          path: /tmp/my_artifact
          destination: eiyuden
      - store_artifacts:
          path: /tmp/bluemoon

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
