default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: discord_log_storage_development

test:
  <<: *default
  database: discord_log_storage_test
  username: <%= ENV['PG_USERNAME'] || 'root' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>

production:
  <<: *default
  database: discord_log_storage_production
